import 'package:flutter/material.dart';

import 'models/share_card_main_image_config.dart';
import 'models/share_card_region.dart';
import 'models/share_card_theme_definition.dart';
import 'models/share_card_theme_slot.dart';
import 'models/share_card_watermark_style.dart';
import 'share_card_theme_presets.dart';

ShareCardThemeDefinition _t(
  String id,
  String label,
  String assetPath,
  double designWidth,
  double designHeight,
  Map<ShareCardThemeSlot, ShareCardRegion> regions,
  ShareCardMainImageConfig mainImage, {
  double safeHorizontalFraction = 0.045,
  double safeVerticalFraction = 0.028,
  bool textShadows = false,
  double mainImageCornerRadiusFraction = 0.02,
  ShareCardWatermarkStyle watermarkStyle = ShareCardWatermarkStyle.none,
  Color? titleColor,
  Color? subtitleColor,
  Color? priceColor,
  Color? accentColor,
  Color? agentTitleColor,
  Color? agentPhoneColor,
  bool useAgentAvatarForLogo = false,
}) {
  return ShareCardThemeDefinition(
    id: id,
    label: label,
    assetPath: assetPath,
    designWidth: designWidth,
    designHeight: designHeight,
    safeHorizontalFraction: safeHorizontalFraction,
    safeVerticalFraction: safeVerticalFraction,
    regions: cloneRegions(regions),
    mainImage: mainImage,
    mainImageCornerRadiusFraction: mainImageCornerRadiusFraction,
    textShadows: textShadows,
    watermarkStyle: watermarkStyle,
    titleColor: titleColor ?? const Color(0xFFFFFFFF),
    subtitleColor: subtitleColor ?? const Color(0xFFE2E8F0),
    priceColor: priceColor ?? const Color(0xFF38BDF8),
    accentColor: accentColor ?? const Color(0xFFF59E0B),
    agentTitleColor: agentTitleColor,
    agentPhoneColor: agentPhoneColor,
    useAgentAvatarForLogo: useAgentAvatarForLogo,
  );
}

/// Central registry: `assets/themes` raster backgrounds + slot geometry.
final List<ShareCardThemeDefinition> shareCardThemes = [
  _t('theme_01', 'Tema 1', 'assets/themes/theme1.png', 1080, 1920, kShareCardRegionsStoryLike, kShareCardMainImageStory,
      safeVerticalFraction: 0.028),
  _t('theme_02', 'Tema 2', 'assets/themes/theme2.jpg', 1080, 1080, kShareCardRegionsSquareSplitNavyLeft,
      kShareCardMainImageSquareSplitRight,
      safeVerticalFraction: 0.04,
      mainImageCornerRadiusFraction: 0.045),
  _t(
    'theme_03',
    'Tema 3',
    'assets/themes/theme3.jpg',
    1080,
    1350,
    kShareCardRegionsPortraitTaupe,
    kShareCardMainImagePortraitTaupe,
    safeVerticalFraction: 0.032,
    titleColor: const Color(0xFF3E322B),
    subtitleColor: const Color(0xFF5C4D42),
    priceColor: const Color(0xFF2D241F),
    accentColor: const Color(0xFF7A5C45),
  ),
  _t('theme_04', 'Tema 4', 'assets/themes/theme4.jpg', 1080, 1080, kShareCardRegionsSquarePhotoLeftCopyRight,
      kShareCardMainImageSquareEditorialLeft,
      safeVerticalFraction: 0.04),
  _t(
    'theme_05',
    'Tema 5',
    'assets/themes/theme5.jpg',
    1080,
    1920,
    kShareCardRegionsStoryFiveGallery,
    kShareCardMainImageStoryFiveHero,
    safeVerticalFraction: 0.028,
    textShadows: true,
    titleColor: const Color(0xFF0F172A),
    subtitleColor: const Color(0xFF475569),
    priceColor: const Color(0xFF0369A1),
    accentColor: const Color(0xFFC2410C),
    agentTitleColor: const Color(0xFFFFFFFF),
    agentPhoneColor: const Color(0xFFE2E8F0),
  ),
  _t('theme_06', 'Tema 6', 'assets/themes/theme6.jpg', 1414, 2000, kShareCardRegionsStoryLike, kShareCardMainImageStory,
      safeVerticalFraction: 0.028),
  _t('theme_07', 'Tema 7', 'assets/themes/theme7.jpg', 1080, 1080, kShareCardRegionsSquareLowerBand,
      kShareCardMainImageSquareLowerHero,
      safeVerticalFraction: 0.04,
      textShadows: true),
  _t('theme_08', 'Tema 8', 'assets/themes/theme8.jpg', 1080, 1080, kShareCardRegionsSquareWood,
      kShareCardMainImageSquareWoodHero,
      safeVerticalFraction: 0.04,
      textShadows: true),
  _t('theme_09', 'Tema 9', 'assets/themes/theme9.jpg', 1080, 1080, kShareCardRegionsSquareMagazineStripe,
      kShareCardMainImageSquareMagazineRail,
      safeVerticalFraction: 0.04,
      textShadows: true),
  _t('theme_10', 'Tema 10', 'assets/themes/theme10.jpg', 1080, 1080, kShareCardRegionsSquarePoolMontage,
      kShareCardMainImageSquarePoolHero,
      safeVerticalFraction: 0.04,
      textShadows: true),
  _t('theme_11', 'Tema 11', 'assets/themes/theme11.jpg', 2000, 1414,
      kShareCardRegionsLandscapeCopyLeftImageRight, kShareCardMainImageLandscapeRightCollage,
      safeHorizontalFraction: 0.04, safeVerticalFraction: 0.045),
  _t(
    'theme_12',
    'Tema 12',
    'assets/themes/theme12.jpg',
    1414,
    2000,
    kShareCardRegionsStory12EditorialCream,
    kShareCardMainImageStory12Hero,
    safeVerticalFraction: 0.024,
    titleColor: const Color(0xFF2B211C),
    subtitleColor: const Color(0xFF4E4039),
    priceColor: const Color(0xFF5D4037),
    accentColor: const Color(0xFF8B7355),
    useAgentAvatarForLogo: true,
  ),
  _t(
    'theme_13',
    'Tema 13',
    'assets/themes/theme13.jpg',
    1414,
    2000,
    kShareCardRegionsStory13OliveSplit,
    kShareCardMainImageStory13Hero,
    safeVerticalFraction: 0.024,
    textShadows: true,
    titleColor: const Color(0xFFFFFFFF),
    subtitleColor: const Color(0xFFECEFF1),
    priceColor: const Color(0xFFFFF9C4),
    accentColor: const Color(0xFFFFF59D),
  ),
  _t(
    'theme_14',
    'Tema 14',
    'assets/themes/theme14.jpg',
    1080,
    1350,
    kShareCardRegionsPortrait14GreenCream,
    kShareCardMainImagePortrait14Hero,
    safeVerticalFraction: 0.03,
    titleColor: const Color(0xFF1B2E16),
    subtitleColor: const Color(0xFF374A35),
    priceColor: const Color(0xFF1B5E20),
    accentColor: const Color(0xFF33691E),
  ),
  _t(
    'theme_15',
    'Tema 15',
    'assets/themes/theme15.jpg',
    1080,
    1350,
    kShareCardRegionsPortrait15BeigeMagazine,
    kShareCardMainImagePortrait15Hero,
    safeVerticalFraction: 0.03,
    titleColor: const Color(0xFF3E3631),
    subtitleColor: const Color(0xFF5C534D),
    priceColor: const Color(0xFF4E342E),
    accentColor: const Color(0xFF6D4C41),
  ),
  _t('hestora_story_default', 'Örnek — Hikaye', 'assets/themes/hestora_story_default.png', 1080, 1920, kShareCardRegionsStoryLike,
      kShareCardMainImageStory,
      safeVerticalFraction: 0.028,
      watermarkStyle: ShareCardWatermarkStyle.light),
  _t('hestora_square_default', 'Örnek — Kare', 'assets/themes/hestora_square_default.png', 1080, 1080, kShareCardRegionsSquare,
      kShareCardMainImageSquare,
      safeVerticalFraction: 0.04,
      watermarkStyle: ShareCardWatermarkStyle.light),
];

/// Yalnızca marka şablonları (`theme_01` … `theme_15`); örnek `hestora_*` temaları dahil değildir.
final List<ShareCardThemeDefinition> shareCardListingThemes =
    shareCardThemes.where((t) => t.id.startsWith('theme_')).toList(growable: false);

ShareCardThemeDefinition shareCardThemeById(String id) {
  return shareCardThemes.firstWhere((t) => t.id == id, orElse: () => shareCardThemes.first);
}
